### ISSUE TITLE
Compatibility with Camful

### ISSUE THREAD

**Issue by SharkieTV** [UghZan/campfireOverhaul#3]
Hi, I want to use your mod in my Modpack "Better Minecraft Modpack", 18K+ Downloads and I have a mod in it called Campful: https://www.curseforge.com/minecraft/mc-mods/campful. It seems that when I light the Campful campfires that they instantly go out. I was hoping you can make it Compatible so I can add it to my Modpack.

Thanks

**Comment by UghZan** [comment]
Ok, I'll try to do it.

**Comment by UghZan** [comment]
I added compatibility using a separate datapack. This isn't exactly the best solution for modpack AFAIK, so you could add the "data" folder of datapack directly to mod jar of Campful (it is loaded after my mod because of alphabetical load order) and it should work. I will look for a better solution, but for now that should do.
